## Exercises XP

### Exercise 1 : Array Creation and Manipulation

In [1]:
import numpy as np

array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 2 : Type Conversion and Array Operations

In [10]:
list_r = [3.14, 2.17, 0, 1, 2]
data_np = np.array(np.round(list_r))
data_int = data_np.astype(int)
print(data_int)


[3 2 0 1 2]


### Exercise 3 : Working with Multi-Dimensional Arrays

In [13]:
array_3x3 = np.arange(1,10).reshape(3,3)
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [16]:
arry_random = np.random.rand(4, 5)
arry_random

array([[0.88981581, 0.19880718, 0.67314601, 0.3795115 , 0.32332974],
       [0.26804093, 0.55651591, 0.69876734, 0.19486017, 0.403677  ],
       [0.90078245, 0.09423507, 0.45930542, 0.33121592, 0.55935262],
       [0.03119646, 0.90544933, 0.74445169, 0.86978758, 0.94689167]])

### Exercise 5 : Indexing Arrays


In [20]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1,:]

array([20, 21, 22, 23, 24])

### Exercise 6 : Reversing elements

In [25]:
array_arr = np.arange(10)
array_rev = np.flip(array_arr) #flip = reverse
array_rev


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Exercise 7 : Identity Matrix

In [30]:
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Exercise 8 : Simple Aggregate Funcs

In [34]:
sum = array_1d.sum()
avrg = array_1d.mean()
print("Sum : ", sum ,", Average :", avrg)

Sum :  45 , Average : 4.5


### Exercise 9 : Create Array and Change its

In [37]:
array_20 = np.arange(1,21).reshape(4,5)
array_20

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

###  Exercise 10 : Conditional Selection of Values

In [39]:
array_20[array_20 %2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])